### ISSUE TITLE
Lista com datas de dias atípicos

### ISSUE THREAD

**Issue by alexandre-mbm** [OSMBrasil/osmdetective#3]
@naoliv e @willemarcel, o que seria isso?

---

Auxílios:
- http://i.imgur.com/rxAkHin.png ‒ pico do dia 27 de fevereiro de 2014
- http://nrenner.github.io/achavi/?changeset=20781751 ‒ uma importação...
- http://naoliv.iq.unesp.br/osm/pico1/ ‒ ranking de mapeadores (tabela)
- http://osmstats.neis-one.org/?item=countries&country=Brazil ‒ gráficos estatísticos

**Comment by alexandre-mbm** [comment]
## Log de IRC
**&#x3C;AlexandreMBM>** wille, sobre o osmdetective: se eu tomei a frente e, sem comunicação, impedi que você se divertisse fazendo algo, desculpe-me. Não achei necessário maiores conversas porque era apenas andar mais um pouco com o esqueleto o mais básico do projeto. Claro que você deve se sentir a vontade para reverter algo. Eu acho que separar o "negócio" do comando get (como fiz) é uma boa forma de começar a organização da caixa de ferramentas do
**&#x3C;AlexandreMBM>**  detetive.
**&#x3C;AlexandreMBM>** * esqueleto do mais básico
**&#x3C;wille>** @alexandrembm1 ok. vou olhar depois
**&#x3C;AlexandreMBM>** wille, se você e o naoliv (e outros) participarem da issue #3, eu tenho algumas ideias para colocar. Coisas como: fazer cache do recuperado e consultas nesse cache.
**&#x3C;AlexandreMBM>** Consultas podem estar num comando "query", seguindo a lógico de ter o "get" (que temos).
**&#x3C;AlexandreMBM>** A opção --cache seria para o "get" e facultativa, para TRUE por padrão.
**&#x3C;AlexandreMBM>** * a lógica de
**&#x3C;AlexandreMBM>** * /para/mas/ TRUE por padrão.
**&#x3C;AlexandreMBM>** Assim, o comando "get" poderia ter uma opção --print (ativada obrigatoriamente se --no-cache).

**Comment by naoliv** [comment]
http://www.openstreetmap.org/user/naoliv/diary/34828
